general:
  # Commands to run when the WM has started (e.g. to run a script or launch
  # another application). Here we are running a batch script to start Zebar.
  startup_commands: ["shell-exec zebar"]
  # Whether to automatically focus windows underneath the cursor.

  focus_follows_cursor: false
  # Whether to switch back and forth between the previously focused

  # workspace when focusing the current workspace.
  toggle_workspace_on_refocus: false
  cursor_jump:
    # Whether to automatically move the cursor on the specified trigger.
    enabled: true
    # Trigger for cursor jump:

    # - 'monitor_focus': Jump when focus changes between monitors.
    # - 'window_focus': Jump when focus changes between windows.
    # trigger: "monitor_focus"
    trigger: "window_focus"
  hide_method: "hide"
gaps:
  # Gap between adjacent windows.
  inner_gap: "10px"
  # Gap between windows and the screen edge.

  outer_gap:
    top: "50px"
    right: "10px"
    bottom: "10px"
    left: "10px"
window_effects:
  # Visual effects to apply to the focused window.
  focused_window:
    # Highlight the window with a colored border.
    # ** Exclusive to Windows 11 due to API limitations.
    border:
      enabled: true
      color: "#bea3c7"
  # Visual effects to apply to non-focused windows.

  other_windows:
    border:
      enabled: true
      color: "#a1a1a1"
    transparency:
      enabled: true
      opacity: "95%"

window_behavior:
  # New windows are created in this state whenever possible.
  # Allowed values: 'tiling', 'floating'.
  initial_state: "tiling"
  # Sets the default options for when a new window is created. This also

  # changes the defaults for when the state change commands, like
  # `set-floating`, are used without any flags.
  state_defaults:
    floating:
      # Whether to center floating windows by default.
      centered: true
      # Whether to show floating windows as always on top.

      shown_on_top: false
    fullscreen:
      # Maximize the window if possible. If the window doesn't have a
      # maximize button, then it'll be fullscreen'ed normally instead.
      maximized: false
      # Whether to show fullscreen windows as always on top.

      shown_on_top: false
workspaces:
  - name: "Outlook"
  - name: "Teams"
  - name: "Chrome"
  - name: "Term"
  - name: "Misc"
  - name: "spec"
  - name: "VS"
  - name: "sys"
  - name: "Remote"
window_rules:
  - commands: ["ignore"]
    match:
      # Ignores any Zebar windows.
      - window_process: {equals: "zebar"}
      - window_title: {regex: "[Pp]icture.in.[Pp]icture"}
        # Ignores picture-in-picture windows for browsers.

        window_class: {regex: "Chrome_WidgetWin_1|MozillaDialogClass"}
      - window_process: {equals: "PowerToys.PowerAccent"}
        # Ignore rules for various 3rd-party apps.
      - window_process: {equals: "Lively"}
        window_class: {regex: "HwndWrapper*"}
binding_modes:
  # When enabled, the focused window can be resized via arrow keys or HJKL.
  - name: "resize"
    keybindings:
      - commands: ["resize --width -2%"]
        bindings: ["h", "left"]
      - commands: ["resize --width +2%"]
        bindings: ["l", "right"]
      - commands: ["resize --height +2%"]
        bindings: ["k", "up"]
      - commands: ["resize --height -2%"]
        bindings: ["j", "down"]
      - commands: ["wm-disable-binding-mode --name resize"]
        # Press enter/escape to return to default keybindings.

        bindings: ["escape", "enter"]
  - name: "pause"
    # When enabled, all keybindings are disabled except for alt+shift+p which

    # returns to default keybindings.
    keybindings:
      - commands: ["wm-disable-binding-mode --name pause"]
        bindings: ["alt+shift+p"]
keybindings:
  # Shift focus in a given direction.
  - commands: ["focus --direction left"]
    bindings: ["alt+h", "alt+left"]
  - commands: ["focus --direction right"]
    bindings: ["alt+l", "alt+right"]
  - commands: ["focus --direction up"]
    bindings: ["alt+k", "alt+up"]
  - commands: ["focus --direction down"]
    bindings: ["alt+j", "alt+down"]
  # Move focused window in a given direction.
  - commands: ["move --direction left"]
    bindings: ["alt+shift+h", "alt+shift+left"]
  - commands: ["move --direction right"]
    bindings: ["alt+shift+l", "alt+shift+right"]
  - commands: ["move --direction up"]
    bindings: ["alt+shift+k", "alt+shift+up"]
  - commands: ["move --direction down"]
    bindings: ["alt+shift+j", "alt+shift+down"]
   # Resize focused window by a percentage or pixel amount.
  - commands: ["resize --width -2%"]
    bindings: ["alt+u"]
  - commands: ["resize --width +2%"]
    bindings: ["alt+p"]
  - commands: ["resize --height +2%"]
    bindings: ["alt+o"]
  - commands: ["resize --height -2%"]
    bindings: ["alt+i"]
  # As an alternative to the resize keybindings above, resize mode enables

  # the name 'resize'.
  # resizing via arrow keys or HJKL. The binding mode is defined above with
  - commands: ["wm-enable-binding-mode --name resize"]
    bindings: ["alt+r"]
  # Disables all keybindings until alt+shift+p is pressed again.
  - commands: ["wm-enable-binding-mode --name pause"]
    bindings: ["alt+shift+p"]

  # Change tiling direction. This determines where new tiling windows will
  - commands: ["toggle-tiling-direction"]
    bindings: ["alt+v"]

  - commands: ["toggle-floating --centered"]
    bindings: ["alt+shift+space"]
    # Change focus from tiling windows -> floating -> fullscreen.

    # Change the focused window to be floating.
    # - commands: ["wm-cycle-focus"]
    # Change the focused window to be tiling.
  - commands: ["toggle-tiling"]
    bindings: ["alt+t"]

    # Change the focused window to be fullscreen.
  - commands: ["toggle-fullscreen"]
    bindings: ["alt+f"]

    # Minimize focused window.
  - commands: ["toggle-minimized"]
    bindings: ["alt+m"]


    # Close focused window.
  - commands: ["close"]
    bindings: ["alt+shift+q"]

    # Kill GlazeWM process safely.
  - commands: ["wm-exit"]
    bindings: ["alt+shift+e"]
    # Re-evaluate configuration file.
  - commands: ["wm-reload-config"]
    bindings: ["alt+shift+r"]
    # Redraw all windows.
  - commands: ["wm-redraw"]
    bindings: ["alt+shift+w"]

  # Launch CMD terminal. Alternatively, use `shell-exec wt` or
  # Terminal and Git Bash respectively.
  # `shell-exec %ProgramFiles%/Git/git-bash.exe` to start Windows
  - commands: ["shell-exec wezterm-gui"]
    bindings: ["alt+enter"]

  - commands: ["focus --next-workspace"]
    bindings: ["alt+w"]
    # Focus the next/previous workspace defined in `workspaces` config.

  - commands: ["focus --prev-workspace"]
    bindings: ["alt+e"]

  - commands: ["focus --recent-workspace"]
    bindings: ["alt+r"]
    # Focus the workspace that last had focus.

    # Change focus to a workspace defined in `workspaces` config.
  - commands: ["focus --workspace Outlook"]
    bindings: ["alt+1"]
  - commands: ["focus --workspace Teams"]
    bindings: ["alt+2"]
  - commands: ["focus --workspace Chrome"]
    bindings: ["alt+3"]
  - commands: ["focus --workspace Term"]
    bindings: ["alt+4"]
  - commands: ["focus --workspace Misc"]
    bindings: ["alt+5"]
  - commands: ["focus --workspace spec"]
    bindings: ["alt+6"]
  - commands: ["focus --workspace VS"]
    bindings: ["alt+7"]
  - commands: ["focus --workspace sys"]
    bindings: ["alt+8"]
  - commands: ["focus --workspace Remote"]
    bindings: ["alt+9"]
  - commands: ["move-workspace --direction left"]
    # Move the focused window's parent workspace to a monitor in a given

    # direction.
    bindings: ["alt+shift+a"]
  - commands: ["move-workspace --direction right"]
    bindings: ["alt+shift+f"]
  - commands: ["move-workspace --direction up"]
    bindings: ["alt+shift+d"]
  - commands: ["move-workspace --direction down"]
    bindings: ["alt+shift+s"]
  - commands: ["move --workspace Outlook", "focus --workspace Outlook"]
    # Move focused window to a workspace defined in `workspaces` config.

    bindings: ["alt+shift+1"]
  - commands: ["move --workspace Teams", "focus --workspace Teams"]
    bindings: ["alt+shift+2"]
  - commands: ["move --workspace Chrome", "focus --workspace Chrome"]
    bindings: ["alt+shift+3"]
  - commands: ["move --workspace Term", "focus --workspace Term"]
    bindings: ["alt+shift+4"]
  - commands: ["move --workspace Misc", "focus --workspace Misc"]
    bindings: ["alt+shift+5"]
  - commands: ["move --workspace spec", "focus --workspace spec"]
    bindings: ["alt+shift+6"]
  - commands: ["move --workspace VS", "focus --workspace VS"]
    bindings: ["alt+shift+7"]
  - commands: ["move --workspace sys", "focus --workspace sys"]
    bindings: ["alt+shift+8"]
  - commands: ["move --workspace Remote", "focus --workspace Remote"]
    bindings: ["alt+shift+9"]
